customhost = "db-employee.czz0hfqvljiq.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "employee"
custombucket = "david-jeremy-jaedon-bucket"
customregion = "us-east-1"
